name: serneity-screenplay-rest-assured CI

on:
  push:
    branches:
    - "master"
    - "feature/*"
  pull_request:
    branches:
    - "master"
    - "feature/*"

jobs:
  setup:
    runs-on: ubuntu-latest
    name: "Configuracion inicial"
    steps:
    - uses: actions/checkout@v2
    - name: Configuracion JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
  compile:
    needs: setup
    runs-on: ubuntu-latest
    name: "Compilacion con Gradle"
    steps:
    - uses: actions/checkout@v2
    - name: Compilacion gradle
      run:  | 
        chmod +x gradlew
        ./gradlew build -x test compileTestJava --info
        
  analysis:
    needs: compile
    runs-on: ubuntu-latest
    name: "Analisis con SonarCloud"
    steps:
    - uses: actions/checkout@v2
    - name: Escaner SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube --info

            
      
