name: serneity-screenplay-rest-assured CI

on:
  push:
    branches:
    - "master"
    - "feature/*"
  pull_request:
    branches:
    - "master"
    - "feature/*"

jobs:
  Configuracion inicial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configuracion JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
  Compilacion:
    needs: Configuracion inicial
    runs-on: ubuntu-latest
    steps:
    - name: Compilacion gradle
      run:  | 
        chmod +x gradlew
        ./gradlew build -x test compileTestJava
        
  Analisis SonarCloud:
    needs: Compilacion
    runs-on: ubuntu-latest
    steps:
    - name: Escaner SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=camillomurcia
          -Dsonar.projectKey=camillomurcia_serenity-screenplay-rest-assured
          -Dsonar.sources=src/main
          -Dsonar.test=src/test
            
      
