name: serneity-screenplay-rest-assured CI

on:
  push:
    branches:
    - "master"
  pull_request:
    branches:
    - "master"

jobs:
  setup:
    runs-on: ubuntu-latest
    name: "Configuracion inicial"
    steps:
    - uses: actions/checkout@v2
    - name: Configuracion JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
  compile:
    needs: setup
    runs-on: ubuntu-latest
    name: "Compilacion con Gradle"
    steps:
    - uses: actions/checkout@v2
    - name: Compilacion gradle
      run:  | 
        chmod +x gradlew
        ./gradlew build -x test compileTestJava --info
        
  analysis:
    needs: compile
    runs-on: ubuntu-latest
    name: "Analisis con SonarCloud"
    steps:
    - uses: actions/checkout@v2
    - name: Escaner SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube --info

  test:
    needs: analysis
    runs-on: ubuntu-latest
    name: "Ejecucion de pruebas"
    steps:
      - uses: actions/checkout@v2
      - name: Ejecucion de pruebas
        run: |
          chmod +x gradlew
          ./gradlew clean test aggregate
      - name: GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.ref == 'refs/heads/master'
        with:
          BRANCH: gh-pages
          FOLDER: target/site/serenity
          CLEAN: true
            
      
